services:
  - type: web
    name: copa-2026
    env: docker
    repo: https://github.com/SEU_USUARIO/copa-2026
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "3000"
      - key: ADMIN_PASSWORD
        value: admin123kol
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
